name: learntern-env
channels:
  - defaults
  - pytorch
  #- nvidia # If you want nvidia hardware acceleration
dependencies:
  # languages
  - python=3.11
  - pip
  #- r # Do we like R more than python?

  # Data Dependencies
  - pandas
  - numpy

  # Visualisation Dependencies
  - ipykernel
  - matplotlib
  - libpng
  - jpeg
  - rich

# Learning Dependencies
  - scikit-learn
  - pip:
    - torch
    - torchvision
    - torchaudio